# MIT License
#
# Copyright (c) 2023 Resha Dwika Hefni Al-Fahsi
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ==============================================================================


from neuralnetwork.ds.medmnist.dataset import (
    PathMNIST,
    OCTMNIST,
    PneumoniaMNIST,
    ChestMNIST,
    DermaMNIST,
    RetinaMNIST,
    BreastMNIST,
    BloodMNIST,
    TissueMNIST,
    OrganAMNIST,
    OrganCMNIST,
    OrganSMNIST,
    OrganMNIST3D,
    NoduleMNIST3D,
    AdrenalMNIST3D,
    FractureMNIST3D,
    VesselMNIST3D,
    SynapseMNIST3D,
    OrganMNISTAxial,
    OrganMNISTCoronal,
    OrganMNISTSagittal,
)
